In [1]:
import pandas as pd

# Mini Desafío (Equipos)

In [165]:
!wget "https://raw.githubusercontent.com/IEEESBITBA/Curso-Python/master/Curso_Analisis_de_Datos_Datos/Tabla1.xlsx"

--2024-10-12 23:29:59--  https://raw.githubusercontent.com/IEEESBITBA/Curso-Python/master/Curso_Analisis_de_Datos_Datos/Tabla1.xlsx
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.110.133, 185.199.109.133, 185.199.108.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.110.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 4909 (4.8K) [application/octet-stream]
Saving to: ‘Tabla1.xlsx.1’

Tabla1.xlsx.1       100%[===================>]   4.79K  --.-KB/s    in 0s

2024-10-12 23:29:59 (58.2 MB/s) - ‘Tabla1.xlsx.1’ saved [4909/4909]

### Mini desafío 1.A
Leer el archivo **Tabla1.xlsx** que contiene los puntos de un campeonato. El archivo tiene cuatro columnas:
* **Equipo**
* **Puntos**
* **Goles a favor**
* **Goles en contra**

Determinar de cada equipo la diferencia de gol (goles a favor - goles en contra), y mostrar todas las diferencias usando **print**.

In [166]:
campeonato_df = pd.read_excel("Tabla1.xlsx")

In [167]:
campeonato_df.sample(3)

     Equipo  Puntos  Goles a favor  Goles en contra
0  Equipo A      30             65               10
1  Equipo B      25             45               15
5  Equipo F      23             45               20

In [168]:
campeonato_df_copy = campeonato_df.copy()

In [169]:
campeonato_df_copy['Diferencia de Gol'] = campeonato_df_copy['Goles a favor'] - campeonato_df_copy['Goles en contra']

In [170]:
campeonato_df_copy

     Equipo  Puntos  Goles a favor  Goles en contra  Diferencia de Gol
0  Equipo A      30             65               10                 55
1  Equipo B      25             45               15                 30
2  Equipo C      27             60               20                 40
3  Equipo D      17             30               60                -30
4  Equipo E      19             25               30                 -5
5  Equipo F      23             45               20                 25

### Mini desafío 1.B - Challenge

Determinar qué equipo es el campeón (**1ro**) y perdedor (**último**). ¿Qué columnas del archivo hay que analizar en este caso?

In [171]:
mayor_puntaje = campeonato_df_copy['Puntos'].max()
mayor_diferencia_de_goles = campeonato_df_copy['Diferencia de Gol'].max()
campeon = campeonato_df_copy[(campeonato_df_copy['Puntos'] == mayor_puntaje) & (campeonato_df_copy['Diferencia de Gol'] == mayor_diferencia_de_goles)]

In [172]:
print("El campeón es:", campeon.loc[0]["Equipo"])

El campeón es: Equipo A

### Mini desafio 1.C - Extra Challenge
Determinar qué equipos obtuvieron mas de 20 puntos, y mostrar sus diferencias de goles.

Plus: ordenar los equipos de mayor a menor en puntaje (de forma descendiente).

In [173]:
puntaje_minimo = 20
campeonato_df_copy[campeonato_df_copy["Puntos"] > puntaje_minimo].sort_values(["Puntos"], ascending=False)

     Equipo  Puntos  Goles a favor  Goles en contra  Diferencia de Gol
0  Equipo A      30             65               10                 55
2  Equipo C      27             60               20                 40
1  Equipo B      25             45               15                 30
5  Equipo F      23             45               20                 25

# Mini Desafío (Alumnos)

In [174]:
!wget "https://raw.githubusercontent.com/IEEESBITBA/Curso-Python/master/Curso_Analisis_de_Datos_Datos/Datos.xlsx"

--2024-10-12 23:30:00--  https://raw.githubusercontent.com/IEEESBITBA/Curso-Python/master/Curso_Analisis_de_Datos_Datos/Datos.xlsx
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.110.133, 185.199.109.133, 185.199.108.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.110.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 4054 (4.0K) [application/octet-stream]
Saving to: ‘Datos.xlsx.1’

Datos.xlsx.1        100%[===================>]   3.96K  --.-KB/s    in 0s

2024-10-12 23:30:00 (57.4 MB/s) - ‘Datos.xlsx.1’ saved [4054/4054]

### Mini desafío 2.A
Calcular el promedio de las notas de química de todos los alumnos en el archivo **Datos.xlsx**.

- **Tip:** Podemos usar la función **sum**($iterable$) para obtener la suma de todos los campos. Un ejemplo de como funciona:
```python
mi_lista = [1, 2, 3, 4, 5]
total = sum(mi_lista)
print(total)
```
 ¡La función **len()** también sigue siendo válida!

In [175]:
alumnos = pd.read_excel("Datos.xlsx", index_col="Legajo")

In [176]:
alumnos.sample(3)

       Nombre  Apellido  Quimica  Matematica  Fisica
Legajo
34567    Juan  Martinez       10           7       9
32578   Tomas       Reu        1           4       2
36789   Paula     Lagos        8           5       8

In [177]:
print(alumnos["Quimica"].mean())

5.666666666666667

### Mini desafío 2.B

Escribir una funcion que reciba como parámetros: una variable de tipo **DataFrame** (la tabla de alumnos) y el índice de un alumno. Luego debe devolver con *return* el promedio de sus notas en las diferentes materias.

In [270]:
def calcular_promedio(df_alumnos: pd.DataFrame, legajo_alumno: int) -> float:
    promedio = df_alumnos.loc[legajo_alumno, ["Quimica", "Matematica", "Fisica"]].mean()
    return promedio

In [179]:
calcular_promedio(alumnos, 34567)

8.666666666666666

### Mini desafío 3

Obtener el promedio general sólo para aquellos alumnos que aprobaron Matemática (con nota `>= 6`) en el archivo **Datos.xlsx**.

In [180]:
nota_para_aprobar = 6

In [181]:
alumnos_aprobados = alumnos[(alumnos["Matematica"] >= nota_para_aprobar)].copy()

In [183]:
alumnos_aprobados["Promedio"] = (alumnos_aprobados["Quimica"] + alumnos_aprobados["Matematica"] + alumnos_aprobados["Fisica"]) / 3

In [184]:
alumnos_aprobados

       Nombre  Apellido  Quimica  Matematica  Fisica  Promedio
Legajo
34567    Juan  Martinez       10           7       9  8.666667
34678   Pablo  Gonzales        4           9       4  5.666667
35679     Sol      Rios        9           8      10  9.000000

# Ejercitación Integradora

## Copy
Temas:
*   **Uso de librerías**
*   **Manejo de archivos**

Armar una función que copie un archivo *.xlsx*, y lo guarde como "Copia 1 - $nombre$", de ya existir debe guardarlo como Copia 2 -, Copia 3 - , ...

Usar la libreria **os** para chequear si existe el archivo. Tips:

- os.path.exists($nombre$) devolverá True si ya existe

- Se puede importar con: `import os`

In [185]:
import os
import shutil

In [186]:
def nombrar_archivo(ruta_archivo: str, archivo_a_copiar: str) -> str:
    numero_copia = 1
    ruta_archivo_copia = f"{ruta_archivo}/Copia {numero_copia} - {archivo_a_copiar}"
    while os.path.exists(ruta_archivo_copia):
        numero_copia += 1
        ruta_archivo_copia = f"{ruta_archivo}/Copia {numero_copia} - {archivo_a_copiar}"

    return ruta_archivo_copia

In [187]:
def guardar_copia_archivo(ruta_archivo: str, nueva_ruta: str) -> None:
    archivo_a_copiar = ruta_archivo.split('/')[-1]
    ruta_archivo_copia = nombrar_archivo(nueva_ruta, archivo_a_copiar)
    shutil.copy2(ruta_archivo, ruta_archivo_copia)
    print(f"Archivo copiado exitosamente como: {ruta_archivo_copia}")

## California Housing

Temas:
*   ***Analísis de información estructurada***
*   ***Librerías***

In [188]:
! wget "https://raw.githubusercontent.com/IEEESBITBA/Curso-Python/master/Curso_Analisis_de_Datos_Datos/california_housing_train.xlsx"

--2024-10-12 23:30:02--  https://raw.githubusercontent.com/IEEESBITBA/Curso-Python/master/Curso_Analisis_de_Datos_Datos/california_housing_train.xlsx
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.109.133, 185.199.110.133, 185.199.111.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.109.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 988464 (965K) [application/octet-stream]
Saving to: ‘california_housing_train.xlsx.1’

california_housing_ 100%[===================>] 965.30K  5.00MB/s    in 0.2s

2024-10-12 23:30:02 (5.00 MB/s) - ‘california_housing_train.xlsx.1’ saved [988464/988464]

Este archivo contiene un conjunto de datos de viviendas de California, el cual fue extraido del censo de nacional estadounidense de 1990. Para mas info sobre el set de datos: https://developers.google.com/machine-learning/crash-course/california-housing-data-description

Extraer la siguiente información:

*   ¿Cuantas casas hay con valor 'median_house_value' mayor a 80000 tomando de la longitud -120  a -118?
*   ¿Cual es el promedio de habitaciones por manzana ('total_rooms') de estas casas?

*   ¿Cual es la casa más cara? ¿Cuántas hay con este valor?

*   Obtener la media y la varianza de la propiedad 'median_house_value'.

**Tip:** ¡Pueden investigar funciones de numpy para conseguir la media y la varianza!  [numpy.var](https://docs.scipy.org/doc/numpy-1.6.0/reference/generated/numpy.var.html)

In [189]:
viviendas_california = pd.read_excel("california_housing_train.xlsx")

In [190]:
viviendas_california.sample(3)

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
2944,-117.77,33.76,19,3532,402,1200,426,11.0124,500001
15455,-122.31,37.93,36,1526,256,696,263,3.5089,261900
9039,-118.97,35.39,38,2121,433,1547,441,2.7740,59500

### ¿Cuantas casas hay con valor 'median_house_value' mayor a 80000 tomando de la longitud -120 a -118?

In [191]:
filtro_longitud = (-120 <= viviendas_california["longitude"]) & (viviendas_california["longitude"] <= -118)
filtro_valor = (viviendas_california['median_house_value'] > 80000)

In [192]:
viviendas_california[(filtro_longitud) & (filtro_valor)].shape[0]

5466

### ¿Cual es el promedio de habitaciones por manzana ('total_rooms') de estas casas?

In [193]:
promedio_habitaciones_por_manzana = viviendas_california['total_rooms'].mean()

In [194]:
print("Promedio habitaciones por manzana:", promedio_habitaciones_por_manzana)

Promedio habitaciones por manzana: 2643.664411764706

### ¿Cual es la casa más cara? ¿Cuántas hay con este valor?

In [195]:
valor_mas_caro = viviendas_california['median_house_value'].max()

In [265]:
casas_mas_caras = viviendas_california[viviendas_california['median_house_value'] == valor_mas_caro]

In [268]:
cantidad_casas_con_valor_mas_caro = casas_mas_caras.shape[0]

In [269]:
print("Cantidad de casas con valor más caro:", cantidad_casas_con_valor_mas_caro)

Cantidad de casas con valor más caro: 814

### Obtener la media y la varianza de la propiedad 'median_house_value'.

In [198]:
media = viviendas_california['median_house_value'].mean()

In [199]:
print("Media:", media)

Media: 207300.91235294117

In [200]:
varianza = viviendas_california['median_house_value'].var()

In [201]:
print("Varianza:", varianza)

Varianza: 13452233601.427639

## Llévame en tu bicicleta

Temas:
*   ***Analisís de información estructurada***
*   ***Librerías***

El gobierno de la Ciudad de Buenos Aires recolecta datos acerca del uso de los servicios de bicicletas públicas (ecobici) y publica [parte de ello](https://data.buenosaires.gob.ar/dataset/bicicletas-publicas)[s](https://www.youtube.com/watch?v=-UV0QGLmYys&ab_channel=CarlosVivesVEVO).


Para este ejemplo usaremos los primeros 10000 viajes de la base de datos del 2021. Están invitados a analizar todos los viajes, pero para ello les recomendamos descargar el archivo y ejecutar su programa en forma local (no en Google Golab).

Se quiere conocer más acerca del uso que le dan los usuarios al sistema, por lo cual su tarea será extraer la siguiente información:

* ¿Qué porcentaje de los viajes se completaron en estado NORMAL?
* ¿Cuál es la duración promedio de cada viaje? (Los datos están en segundos)
* ¿A qué hora del día se realizaron más viajes? (por ejemplo: de 16hs a 17hs)
* ¿Cuántas estaciones diferentes fueron utilizadas?
* Para cada estación utilizada como inicio de un viaje, imprimirlas ordenadas por cantidad de viajes que iniciaron de la misma.

**Tip:** Recuerden investigar los métodos que tienen los DataFrames para ver si alguno de ellos les ayuda a resolver un problema particular.

In [202]:
! wget "https://raw.githubusercontent.com/IEEESBITBA/Curso-Python/master/Curso_Analisis_de_Datos_Datos/recorridos-realizados-2021-sample.csv"

--2024-10-12 23:30:05--  https://raw.githubusercontent.com/IEEESBITBA/Curso-Python/master/Curso_Analisis_de_Datos_Datos/recorridos-realizados-2021-sample.csv
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.109.133, 185.199.110.133, 185.199.108.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.109.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 1370907 (1.3M) [text/plain]
Saving to: ‘recorridos-realizados-2021-sample.csv.1’

recorridos-realizad 100%[===================>]   1.31M  6.51MB/s    in 0.2s

2024-10-12 23:30:06 (6.51 MB/s) - ‘recorridos-realizados-2021-sample.csv.1’ saved [1370907/1370907]

In [203]:
viajes = pd.read_csv("recorridos-realizados-2021-sample.csv")

In [204]:
viajes.sample(3)

,ID,Estado cerrado,Duración,Id de estación de inicio,Fecha de inicio,Nombre de estación de inicio,Fecha de fin,Id de estación de fin de viaje,Nombre de estación de fin de viaje,ID de ciclista,Tipo de ciclista,Modelo de bicicleta,Origen de viaje
5995,11197386,NORMAL,1605,5,2021-06-01 13:28:57,005 - Plaza Italia,2021-06-01 13:55:42,2.0,002 - Retiro I,771494,MEMBER,ICONIC,CODE
9750,11193210,NORMAL,505,213,2021-05-31 20:49:49,136 - Acevedo,2021-05-31 20:58:14,54.0,054 - Acuña de Figueroa,194863,MEMBER,ICONIC,CODE
1354,11203073,NORMAL,649,150,2021-06-02 13:24:41,150 - RODRIGO BUENO,2021-06-02 13:35:30,172.0,172 - BRASIL,739206,MEMBER,ICONIC,CODE

### ¿Qué porcentaje de los viajes se completaron en estado NORMAL?

In [205]:
porcentaje_viajes_normales_completados = viajes["Estado cerrado"].value_counts(normalize=True)["NORMAL"] * 100

In [206]:
print("Porcentaje de viajes normales completados:", porcentaje_viajes_normales_completados)

Porcentaje de viajes normales completados: 97.87978797879788

### ¿Cuál es la duración promedio de cada viaje?

In [207]:
promedio_duracion_viajes = viajes['Duración'].mean()

In [208]:
print("Promedio de duración de los viajes:", promedio_duracion_viajes)

Promedio de duración de los viajes: 1089.5680568056805

### ¿A qué hora del día se realizaron más viajes?

In [209]:
fecha_inicio = pd.to_datetime(viajes['Fecha de inicio'])

In [210]:
viajes_por_hora = fecha_inicio.groupby(fecha_inicio.dt.hour).count()

In [211]:
mayor_cantidad_viajes = viajes_por_hora.max()
hora_con_mas_viajes = viajes_por_hora[viajes_por_hora.eq(mayor_cantidad_viajes)].index[0]

In [212]:
print("La mayor cantidad de viajes se realizaron durante la hora:", hora_con_mas_viajes)

La mayor cantidad de viajes se realizaron durante la hora: 15

### ¿Cuántas estaciones diferentes fueron utilizadas?

In [213]:
estaciones_utilizadas = set(pd.concat([viajes['Id de estación de inicio'], viajes['Id de estación de fin de viaje']]))

In [214]:
cantidad_estaciones_utilizadas = len(estaciones_utilizadas)

In [215]:
print("Cantidad de estaciones utilizadas:", cantidad_estaciones_utilizadas)

Cantidad de estaciones utilizadas: 230

### Para cada estación utilizada como inicio de un viaje, imprimirlas ordenadas por cantidad de viajes que iniciaron de la misma.

In [216]:
cantidad_viajes_por_estacion = viajes.groupby('Nombre de estación de inicio').agg(cantidad=('Nombre de estación de inicio', 'count'))

In [217]:
cantidad_viajes_por_estacion.sort_values(by="cantidad")

                                cantidad
Nombre de estación de inicio
309 - UTN II                           1
114 - DELLA PAOLERA                    5
191 - Rivadavia y 9 de Julio           6
361 - Plaza Don Segundo Sombra         6
367 - Eva Perón                        6
...                                  ...
009 - Parque Las Heras               103
161 - Humahuaca                      106
113 - Guatemala                      107
147 - Constitución                   117
005 - Plaza Italia                   120

[229 rows x 1 columns]

## El tiempo es dinero

Temas:
*   ***Analisís de información estructurada***
*   ***Librerías***

La administración del dinero es una tarea que requiere una altísima fiabilidad.
En esta ocasión tu objetivo será programar un script que **actualize la cantidad** de dinero de una serie de usuarios a partir de la información de las transferencias que fueron realizadas.
Más concretamente recibiras una **base de datos con la cantidad de dinero de una serie de usuarios**, un base de datos con una serie de transferencias que los usuarios se realizan entre si, y deberás generar con eso **una nueva base de datos con el dinero actualizado de cada usuario**.

*   Importar el archivo **Finanzas.xlsx** que contiene la cantidad de dinero de los usuarios y las transferencias en dos hojas de archivo.
*   Exportar un archivo **usuarios_actualizados.xlsx** que contiene las cantidades de dinero actualizadas.

In [218]:
! wget "https://raw.githubusercontent.com/IEEESBITBA/Curso-Python/master/Curso_Analisis_de_Datos_Datos/Finanzas.xlsx"

--2024-10-12 23:30:06--  https://raw.githubusercontent.com/IEEESBITBA/Curso-Python/master/Curso_Analisis_de_Datos_Datos/Finanzas.xlsx
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.109.133, 185.199.108.133, 185.199.111.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.109.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 10809 (11K) [application/octet-stream]
Saving to: ‘Finanzas.xlsx.1’

Finanzas.xlsx.1     100%[===================>]  10.56K  --.-KB/s    in 0.001s

2024-10-12 23:30:07 (12.3 MB/s) - ‘Finanzas.xlsx.1’ saved [10809/10809]

Debes procesar las transferencias y actualizar el saldo de cada usuario (crear un nuevo archivo excel con los saldos actualizados).

In [219]:
usuarios = pd.read_excel("Finanzas.xlsx", sheet_name="Usuarios", index_col="Usuario")

In [220]:
usuarios.sample(3)

         Edad  Presupuesto
Usuario
Claudia    43        43433
Joaquin    65        34521
Agustin    22        23432

In [221]:
transferencias = pd.read_excel("Finanzas.xlsx", sheet_name="Transferencias")

In [222]:
transferencias.sample(3)

   Emisor Receptor   Monto Efectuada
3   Uriel  Joaquin   12423        No
1   Rocio    Ariel    2000        No
4  Martin   Andrés  234223        No

### Copias DataFrames

In [223]:
usuarios_copy = usuarios.copy()

In [224]:
transferencias_copy = transferencias.copy()

### Extraer dinero

In [225]:
transferencias_emitidas = transferencias[["Emisor", "Monto"]]

In [226]:
monto_extraido_por_usuario = transferencias_emitidas.groupby("Emisor").agg(Monto=("Monto", "sum"))

In [227]:
def extraer_dinero_de_cuentas(cuentas: pd.DataFrame, dinero_a_extraer: pd.DataFrame) -> None:
    for usuario in dinero_a_extraer.index:
        cuentas.loc[usuario, "Presupuesto"] = cuentas.loc[usuario, "Presupuesto"] + dinero_a_extraer.loc[usuario, "Monto"]

In [228]:
extraer_dinero_de_cuentas(usuarios_copy, monto_extraido_por_usuario)

### Ingresar dinero

In [229]:
transferencias_recibidas = transferencias[["Receptor", "Monto"]]

In [230]:
monto_recibido_por_usuario = transferencias_recibidas.groupby("Receptor").agg(Monto=("Monto", "sum"))

In [231]:
def ingresar_dinero_en_cuentas(cuentas: pd.DataFrame, dinero_ingresado: pd.DataFrame) -> None:
    for usuario in dinero_ingresado.index:
        cuentas.loc[usuario, "Presupuesto"] = cuentas.loc[usuario, "Presupuesto"] + dinero_ingresado.loc[usuario, "Monto"]

In [232]:
ingresar_dinero_en_cuentas(usuarios_copy, monto_recibido_por_usuario)

### Guardar archivo

In [233]:
usuarios_copy.to_excel("FinanzasActualizadas.xlsx")

## Gastos y descuentos

Utilizando esta información acerca de las ventas registradas por un supermercado a lo largo de un día.  

Averigüe cuál fue el número vendido de cada uno de los productos.
Determine cuáles clientes gastaron más de 50 pesos y ofrézcales un descuento la próxima vez que visiten el local.
Calcule cuánto gasta un cliente promedio en un dia en el local.

Ejemplo de funcionamiento:

Datos:

| Nombre   | Producto compardo | Numero comprado | Valor del producto |
| -------- | ------- | -------- | ------- |
| Miguel   | Pan     | 12   | 5    |
| Franco   | Pan     | 2   | 5    |

Salida:

'Hay que comprar 14 unidades de Pan para el dia siguiente'

'Cliente/a Miguel le queremos ofrecer una promocion para la proxima vez que visite la tienda!!'

In [234]:
! wget "https://raw.githubusercontent.com/IEEESBITBA/Curso-Python/master/Curso_Analisis_de_Datos_Datos/datosClientes.xlsx"

--2024-10-12 23:30:07--  https://raw.githubusercontent.com/IEEESBITBA/Curso-Python/master/Curso_Analisis_de_Datos_Datos/datosClientes.xlsx
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.108.133, 185.199.109.133, 185.199.110.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.108.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 5126 (5.0K) [application/octet-stream]
Saving to: ‘datosClientes.xlsx.1’

datosClientes.xlsx. 100%[===================>]   5.01K  --.-KB/s    in 0s

2024-10-12 23:30:07 (41.9 MB/s) - ‘datosClientes.xlsx.1’ saved [5126/5126]

In [235]:
datos = pd.read_excel("datosClientes.xlsx")

In [236]:
datos.sample(3)

     Nombre Producto comprado  Numero comprado  Valor del producto
8     Karen              Cafe               14                   8
1     Pedro         Chocolate                5                  10
6  Josefina              Cafe               22                   8

### Copia DataFrame

In [237]:
datos_copy = datos.copy()

### Productos a reponer

In [238]:
cantidad_vendida_por_producto = datos_copy.groupby("Producto comprado").agg(cantidad=("Numero comprado", "sum"))

In [239]:
cantidad_vendida_por_producto

                   cantidad
Producto comprado
Cafe                     68
Chicle                   55
Chocolate                17
Huevos                   36
Te                       25

In [240]:
for producto in cantidad_vendida_por_producto.index:
    print(f"Hay que reponer {cantidad_vendida_por_producto.loc[producto]['cantidad']} unidad/es de {producto}")

Hay que reponer 68 unidad/es de Cafe
Hay que reponer 55 unidad/es de Chicle
Hay que reponer 17 unidad/es de Chocolate
Hay que reponer 36 unidad/es de Huevos
Hay que reponer 25 unidad/es de Te

### Clientes con descuento

In [241]:
datos_copy["Dinero gastado"] = datos_copy["Numero comprado"] * datos_copy["Valor del producto"]

In [242]:
dinero_gastado_por_cliente = datos_copy.groupby("Nombre").agg(Dinero_gastado=("Dinero gastado", "sum"))

In [243]:
valor_minimo_para_descuento = 50
clientes_con_descuento = dinero_gastado_por_cliente[dinero_gastado_por_cliente["Dinero_gastado"] >= valor_minimo_para_descuento]

In [244]:
for cliente in clientes_con_descuento.index:
    print(f"Cliente/a {cliente} le queremos ofrecer una promocion para la proxima vez que visite la tienda!!")

Cliente/a Ezequiel le queremos ofrecer una promocion para la proxima vez que visite la tienda!!
Cliente/a Josefina le queremos ofrecer una promocion para la proxima vez que visite la tienda!!
Cliente/a Juan le queremos ofrecer una promocion para la proxima vez que visite la tienda!!
Cliente/a Julieta le queremos ofrecer una promocion para la proxima vez que visite la tienda!!
Cliente/a Karen le queremos ofrecer una promocion para la proxima vez que visite la tienda!!
Cliente/a Martin le queremos ofrecer una promocion para la proxima vez que visite la tienda!!
Cliente/a Pedro le queremos ofrecer una promocion para la proxima vez que visite la tienda!!
Cliente/a Riquelme le queremos ofrecer una promocion para la proxima vez que visite la tienda!!
Cliente/a Valentina le queremos ofrecer una promocion para la proxima vez que visite la tienda!!

## Unificación de bases de datos

El objetivo de este problema es unificar dos bases de datos que contienen mails. Esto quiere decir, tomar dos bases de datos de formato *.csv*: **lista1.csv** y **lista2.csv** y combinarlas en una misma base de datos **listafinal.csv**.
El contenido de las bases de datos son listas de mails, que contienen mails y otras informaciones de distintos usuarios. Tener en cuenta que las dos bases de datos pueden tener informaciones distintas de los usuarios.

**Recomendamos** descargar los archivos para ver su contenido (Con excel pueden abrirlos, pensar que un csv es prácticamente equivalente a un excel).

In [245]:
! wget "https://raw.githubusercontent.com/IEEESBITBA/Curso-Python/master/Curso_Analisis_de_Datos_Datos/lista1.csv"
# primera lista de clientes

! wget "https://raw.githubusercontent.com/IEEESBITBA/Curso-Python/master/Curso_Analisis_de_Datos_Datos/lista2.csv"
# segunda lista de clientes

! wget "https://raw.githubusercontent.com/IEEESBITBA/Curso-Python/master/Curso_Analisis_de_Datos_Datos/lista_final.csv"
# ejemplo de como tiene que quedar (las columnas pueden quedar en otro orden! salvo la primera)

--2024-10-12 23:30:08--  https://raw.githubusercontent.com/IEEESBITBA/Curso-Python/master/Curso_Analisis_de_Datos_Datos/lista1.csv
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.111.133, 185.199.109.133, 185.199.108.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.111.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 139 [text/plain]
Saving to: ‘lista1.csv.1’

lista1.csv.1        100%[===================>]     139  --.-KB/s    in 0s

2024-10-12 23:30:08 (6.70 MB/s) - ‘lista1.csv.1’ saved [139/139]

--2024-10-12 23:30:08--  https://raw.githubusercontent.com/IEEESBITBA/Curso-Python/master/Curso_Analisis_de_Datos_Datos/lista2.csv
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.111.133, 185.199.109.133, 185.199.108.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.111.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 195 [text/plain]
Saving to: ‘lista2.csv.1’

lista2.csv.1        100%[===================>]     195  --.-KB/s    in 0s

2024-10-12 23:30:09 (10.7 MB/s) - ‘lista2.csv.1’ saved [195/195]

--2024-10-12 23:30:09--  https://raw.githubusercontent.com/IEEESBITBA/Curso-Python/master/Curso_Analisis_de_Datos_Datos/lista_final.csv
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.109.133, 185.199.108.133, 185.199.111.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.109.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 279 [text/plain]
Saving to: ‘lista_final.csv.1’

lista_final.csv.1   100%[===================>]     279  --.-KB/s    in 0s

2024-10-12 23:30:09 (4.66 MB/s) - ‘lista_final.csv.1’ saved [279/279]

#### DataFrame1

In [246]:
dataframe1 = pd.read_csv("https://raw.githubusercontent.com/IEEESBITBA/Curso-Python/master/Curso_Analisis_de_Datos_Datos/lista1.csv")

In [247]:
dataframe1.head()

                  Mail  Apellido    Nombre  Edad
0     druschel@msn.com  Druschel   Julieta    31
1  hstiles@hotmail.com    Stiles     Harry    23
2    jrifkin@gmail.com    Rifkin  Josefina    27

### DataFrame2

In [248]:
dataframe2 = pd.read_csv("https://raw.githubusercontent.com/IEEESBITBA/Curso-Python/master/Curso_Analisis_de_Datos_Datos/lista2.csv")

In [249]:
dataframe2.head()

                  Mail    Nombre Apellido       DNI
0    payned@icloud.com     Pedro    Ayned  23569875
1    johnh@comcast.net      John   Harris  99852365
2  fairbank@icloud.com  Fernanda  Airbank  99754231
3    jrifkin@gmail.com  Josefina   Rifkin  40896523

### Copias DataFrames

In [250]:
dataframe1_copy = dataframe1.copy()

In [251]:
dataframe2_copy = dataframe2.copy()

### Merge DataFrame1 y DataFrame2

In [252]:
merge_dataframe1_y_dataframe2 = dataframe1_copy.merge(dataframe2_copy, how="outer", on="Mail")

In [253]:
merge_dataframe1_y_dataframe2["Apellido_x"] = merge_dataframe1_y_dataframe2["Apellido_x"].combine_first(merge_dataframe1_y_dataframe2["Apellido_y"])
merge_dataframe1_y_dataframe2["Nombre_x"] = merge_dataframe1_y_dataframe2["Nombre_x"].combine_first(merge_dataframe1_y_dataframe2["Nombre_y"])

In [254]:
merge_dataframe1_y_dataframe2.drop(columns=["Apellido_y", "Nombre_y"], inplace=True)

In [255]:
merge_dataframe1_y_dataframe2.head()

                  Mail Apellido_x  Nombre_x  Edad         DNI
0     druschel@msn.com   Druschel   Julieta  31.0         NaN
1  fairbank@icloud.com    Airbank  Fernanda   NaN  99754231.0
2  hstiles@hotmail.com     Stiles     Harry  23.0         NaN
3    johnh@comcast.net     Harris      John   NaN  99852365.0
4    jrifkin@gmail.com     Rifkin  Josefina  27.0  40896523.0

### DataFrame Final

In [256]:
dataframe_final = pd.read_csv("https://raw.githubusercontent.com/IEEESBITBA/Curso-Python/master/Curso_Analisis_de_Datos_Datos/lista_final.csv")

In [257]:
dataframe_final.head()

            Unnamed: 0    Nombre  Apellido       DNI Edad
0     druschel@msn.com   Julieta  Druschel         -   31
1  fairbank@icloud.com  Fernanda   Airbank  99754231    -
2  hstiles@hotmail.com     Harry    Stiles         -   23
3    johnh@comcast.net      John    Harris  99852365    -
4    jrifkin@gmail.com  Josefina    Rifkin  40896523   27

#### Copia DataFrame Final

In [258]:
dataframe_final_copy = dataframe_final.copy()

#### Merge DataFrame Final con DataFrame 1y2

In [259]:
dataframe_final_copy.rename(columns={"Unnamed: 0":"Mail"}, inplace=True)

In [260]:
dataframe_final_actualizado = dataframe_final_copy.merge(merge_lista1_y_lista2, how="outer", on="Mail")

In [261]:
dataframe_final_actualizado["DNI_x"] = dataframe_final_actualizado["DNI_x"].combine_first(dataframe_final_actualizado["DNI_y"])
dataframe_final_actualizado["Edad_x"] = dataframe_final_actualizado["Edad_x"].combine_first(dataframe_final_actualizado["Edad_y"])

In [262]:
dataframe_final_actualizado.drop(columns=["Apellido_x", "Nombre_x", "Edad_y", "DNI_y"], inplace=True)

In [263]:
dataframe_final_actualizado.rename(columns={"DNI_x":"DNI", "Edad_x":"Edad"}, inplace=True)

In [264]:
dataframe_final_actualizado.head()

                  Mail    Nombre  Apellido       DNI Edad
0     druschel@msn.com   Julieta  Druschel         -   31
1  fairbank@icloud.com  Fernanda   Airbank  99754231    -
2  hstiles@hotmail.com     Harry    Stiles         -   23
3    johnh@comcast.net      John    Harris  99852365    -
4    jrifkin@gmail.com  Josefina    Rifkin  40896523   27

# **Opcional**: Mini-desafío json
Estás encargado de un servidor con millones de usuarios.

Se pide escribir un programa que reciba el email y contraseña del usuario y se fije si existe el usuario y si coincide la contraseña.

Se tienen datos encolumnados en formato json que nos llegan del siguiente formato:
```json
{
	"usuarios": ["mica@mail.co", "jerry@gma.com","alber@soup.co"],
	"contra": ["abc123","caballitos","yoloswag"]
}
```
La entrada del programa son tres lineas, el programa entonces va tener tres `input()`. La primer linea contiene el `json`, la segunda el `email` a verificar, y la tercera la `contraseña`. Por ende, las primeras lineas de su programa podrían ser:
```python
import json
usuarios = json.loads(input())
email = input()
password = input()
```

La salida del programa será `OK` si el usuario **se encuentra en la base de datos** ***y*** **si coincide la contraseña**, imprimimos `DNE` (does not exist) si el usuario no existe y `NO` en cualquier otro caso.

#### Caso ejemplo
**Entrada**:
```plaintext
{"usuarios": ["mica@mail.co","jerry@gma.com","alber@soup.co"],"contra": ["abc123","caballitos","yoloswag"]}
mica@mail.co
caballitos
```
El usuario existe y la contraseña también... pero no le corresponde la contraseña `caballitos` al usuario `mica@mail.co` (la contraseña de `mica@mail.co` sería `abc123`) por ende imprimimos:

**Salida**
```
NO
```

_Considere que no hay usuarios repetidos_.

In [ ]:
import json as js

In [ ]:
USUARIOS = ({"usuarios": ["mica@mail.co","jerry@gma.com","alber@soup.co"],"contra": ["abc123","caballitos","yoloswag"]})

In [ ]:
def comprobar_datos(mail: str, contra: str) -> bool:
    es_mail_valido = False
    if mail in USUARIOS["usuarios"]:
        indice_usuario = USUARIOS["usuarios"].index(mail)
        if contra == USUARIOS["contra"][indice_usuario]:
            es_mail_valido = True
            print("\033[92m" + "OK" + "\033[0m")
        else:
            print("\033[91m" + "NO" + "\033[0m")
    else:
        print("\033[91m" + "DNE" + "\033[0m")

    return es_mail_valido

In [ ]:
def iniciar_sesion():
    mail = input("Ingrese su mail: ")
    contra = input("Ingrese su contraseña: ")
    comprobar_datos(mail, contra)

## Ejemplos

In [ ]:
iniciar_sesion()

Ingrese su mail: mica@mail.co
Ingrese su contraseña: abc123
OK

In [ ]:
iniciar_sesion()

Ingrese su mail: mailNoExiste@mail.com
Ingrese su contraseña: 123
DNE

In [ ]:
iniciar_sesion()

Ingrese su mail: mica@mail.co
Ingrese su contraseña: 456
NO